### ISSUE TITLE
 Only v47?

### ISSUE THREAD

**Issue by TheRealMrKam** [willis81808/LethalCompany-AutoWalk#1] opened 2024-01-09 22:46 UTC
It's not working for me on v45, i have the dependencies, the hotkey does appear in the menu but nothing happen when i press it

**Comment by willis81808** [comment] 2024-01-20 23:58
Issue has been identified to be caused by a defect in the LethalCompany Input Utils.
Fixed in version 0.0.4

**Closed as completed by willis81808** 2024-01-20 23:58 UTC
